// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace QueueConsumer.Data
{
    public partial class SessionMessages
    {
        public int Id { get; set; }
        public int? InputId { get; set; }
    }
}