// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Threading.Tasks;
using Microsoft.Azure.Services.AppAuthentication;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ManagedIdentityDemo.Models
{

    public partial class SqldatabaseContext : DbContext
    {
        public SqldatabaseContext()
        {
        }

        public SqldatabaseContext(DbContextOptions<SqldatabaseContext> options)
            : base(options)
        {

        }

        public virtual DbSet<Customers> Customers { get; set; }

        //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //{
        //    SqlConnection connection = new SqlConnection();
        //    //connection.ConnectionString = "Server=sqlserver20210815.database.windows.net;Database=sqldatabase;User Id=kamal;Password=Hello@12345#;";
        //    connection.ConnectionString = "Server=sqlserver2021102311.database.windows.net;Database=sqldatabase;";
        //    AzureServiceTokenProvider provider = new AzureServiceTokenProvider();
        //    var token = provider.GetAccessTokenAsync("https://database.windows.net").GetAwaiter().GetResult();
        //    //connection.AccessToken = token;
        //    optionsBuilder.UseSqlServer(connection);
        //}
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customers>(entity =>
            {
                entity.Property(e => e.Name).HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}