apiVersion: v1
kind: Service
metadata:
  name: my-first-app-lb
  namespace: default
spec:
  selector:
    app: my-first-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP